import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link';
import { useEffect, useState } from 'react';
import Stamp from '../components/Stamp'
import styles from '../styles/Home.module.css'

export default function Home() {
  const [activeTheme, setActiveTheme] = useState('dark');
  const inactiveTheme = activeTheme === 'dark' ? 'light' : 'dark' 

  useEffect(() => {
    document.body.dataset.theme = activeTheme;
  }, []);

  useEffect(() => {
    const savedTheme = JSON.parse(localStorage.getItem('saved-theme'))
  if (savedTheme) {
    setActiveTheme(savedTheme)
    }
  }, [])
  
  useEffect(() => {
    localStorage.setItem(
      'saved-theme',
      JSON.stringify(activeTheme)
    )
  }, [activeTheme])

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
      <Stamp/>
      </main>

      <footer className={styles.footer}>
        <p><span><Link href='/'>Stamp</Link></span> by <a href="https://www.robinn.io/"
        target="_blank"
        rel="noopener noreferrer"
        >Robin Naghshbandi <span className={styles.pass}>💮</span></a></p>
        <br/>
        <a className={styles.source} href="https://github.com/robbandi/stamp"
        target="_blank"
        rel="noopener noreferrer"
        >View source on GitHub</a>
      </footer> 
    </div>
  )
}
